run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused constants, variables, functions
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable, extensible, flexible linter
    - gosec         # Security-focused linter
    - gocritic      # Provides diagnostics that check for bugs, performance, and style issues
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code cloning detection
    - unconvert     # Remove unnecessary type conversions
    # prealloc disabled - optimization suggestion, not critical

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Memory optimization, not critical for v1.0
    settings:
      shadow:
        strict: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/felixgeelhaar/specular

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - whyNoLint       # Too verbose, nolint is self-explanatory in context
      - hugeParam       # Struct size suggestions are opinionated
      - rangeValCopy    # Performance optimization, not critical for v1.0
      - emptyStringTest # len(s) > 0 vs s != "" is style preference
      - appendAssign    # append patterns are valid Go idioms
      - ifElseChain     # if-else chains are often clearer than switches
      - paramTypeCombine # Parameter combining is style preference

  gosec:
    excludes:
      - G204  # Subprocess with variable - needed for Docker execution
      - G304  # File path from variable - needed for file operations

  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - govet
        - gocritic  # Exclude octalLiteral and other style suggestions in tests

    # Exclude E2E test files
    - path: test/e2e/
      linters:
        - errcheck
        - gosec
        - govet

    # Exclude non-critical linters from internal files needing refactoring (v1.1)
    - path: internal/(exec|eval|workflow)/
      linters:
        - govet    # Shadow declarations - refactor in v1.1
        - dupl     # Duplicate code - refactor in v1.1
        - errcheck # Some unchecked errors - audit in v1.1
        - gosec    # File permissions - review in v1.1
        - gocyclo  # Complexity - refactor in v1.1

    # Exclude from plan/policy/prd files (simple data structures)
    - path: internal/(plan|policy|prd)/
      linters:
        - govet    # Shadow declarations - simple loader files
        - gosec    # File permissions - refactor in v1.1

    # Exclude from interview files (interactive CLI, acceptable complexity/style)
    - path: internal/interview/
      linters:
        - gocritic  # Style suggestions - refactor in v1.1
        - gosimple  # Simplification suggestions - refactor in v1.1
        - revive    # Export comments - add in v1.1
        - gocyclo   # Interview flow complexity is acceptable

    # Exclude from progress indicator (display code, unchecked errors acceptable)
    - path: internal/progress/
      linters:
        - errcheck  # Display functions, errors not critical

    # Exclude from provider implementations (refactor in v1.1)
    - path: internal/provider/
      linters:
        - govet       # Shadow declarations - refactor in v1.1
        - dupl        # Duplicate code across providers - extract common logic in v1.1
        - errcheck    # Some unchecked errors - audit in v1.1
        - gosec       # File permissions - review in v1.1
        - ineffassign # Ineffectual assignments - clean up in v1.1
        - gocyclo     # Complexity - refactor in v1.1
        - staticcheck # Unused values - clean up in v1.1

    # Exclude from router (complex routing logic, refactor in v1.1)
    - path: internal/router/
      linters:
        - govet       # Shadow declarations - refactor in v1.1
        - gosec       # File permissions - review in v1.1
        - gocyclo     # Routing complexity - acceptable for v1.0
        - errcheck    # RecordUsage errors - audit in v1.1
        - gocritic    # Style suggestions - refactor in v1.1
        - revive      # Export comments - add in v1.1
        - staticcheck # Empty branches in tests - clean up in v1.1

    # Exclude from spec loader (simple data structures, refactor in v1.1)
    - path: internal/spec/
      linters:
        - govet    # Shadow declarations - simple loader files
        - gosec    # File permissions - review in v1.1
        - errcheck # Some unchecked errors - audit in v1.1

    # Exclude from external provider executables (standalone binaries, refactor in v1.1)
    - path: providers/
      linters:
        - gocyclo  # Handler complexity - refactor in v1.1
        - govet    # Shadow declarations - refactor in v1.1
        - errcheck # Some unchecked errors - audit in v1.1
        - gosec    # Unhandled errors - audit in v1.1

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
