name: 'Specular CI'
description: 'AI-Native Spec and Build Assistant with policy enforcement for CI/CD'
author: 'Felix Geelhaar'
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  version:
    description: 'Version of Specular to use (default: latest)'
    required: false
    default: 'latest'

  command:
    description: 'Specular command to run (drift, eval, build, plan)'
    required: true

  spec-file:
    description: 'Path to spec file'
    required: false
    default: '.specular/spec.yaml'

  plan-file:
    description: 'Path to plan file'
    required: false
    default: 'plan.json'

  policy-file:
    description: 'Path to policy file'
    required: false
    default: '.specular/policy.yaml'

  fail-on:
    description: 'Comma-separated list of conditions to fail on (drift,lint,test,security)'
    required: false
    default: 'drift,test,security'

  sarif-output:
    description: 'Path to SARIF output file for GitHub Code Scanning'
    required: false
    default: 'specular-results.sarif'

  upload-sarif:
    description: 'Upload SARIF results to GitHub Code Scanning'
    required: false
    default: 'true'

  anthropic-api-key:
    description: 'Anthropic API key for AI providers'
    required: false

  openai-api-key:
    description: 'OpenAI API key for AI providers'
    required: false

  google-api-key:
    description: 'Google API key for AI providers'
    required: false

  additional-args:
    description: 'Additional arguments to pass to Specular command'
    required: false
    default: ''

outputs:
  result:
    description: 'Result of the Specular command execution (success/failure)'

  drift-count:
    description: 'Number of drift violations detected'

  test-count:
    description: 'Number of test failures'

  security-count:
    description: 'Number of security issues found'

  sarif-file:
    description: 'Path to generated SARIF file'

runs:
  using: 'composite'
  steps:
    - name: Install Specular
      shell: bash
      run: |
        if [ "${{ inputs.version }}" == "latest" ]; then
          VERSION=$(curl -s https://api.github.com/repos/felixgeelhaar/specular/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
        else
          VERSION="${{ inputs.version }}"
        fi

        echo "Installing Specular $VERSION..."

        # Detect platform
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        case "$ARCH" in
          x86_64) ARCH="amd64" ;;
          aarch64|arm64) ARCH="arm64" ;;
        esac

        # Download and install
        DOWNLOAD_URL="https://github.com/felixgeelhaar/specular/releases/download/${VERSION}/specular_${VERSION#v}_${OS}_${ARCH}.tar.gz"

        echo "Downloading from: $DOWNLOAD_URL"
        curl -sL "$DOWNLOAD_URL" | tar xz -C /tmp
        sudo mv /tmp/specular /usr/local/bin/
        sudo chmod +x /usr/local/bin/specular

        # Install completions
        if [ -d /tmp/completions ]; then
          mkdir -p ~/.local/share/bash-completion/completions
          cp /tmp/completions/specular.bash ~/.local/share/bash-completion/completions/specular 2>/dev/null || true
        fi

        specular version

    - name: Setup AI Provider Credentials
      shell: bash
      run: |
        mkdir -p ~/.specular

        # Create provider config
        cat > ~/.specular/config.yaml <<'INNEREOF'
        providers:
        INNEREOF

        if [ -n "${{ inputs.anthropic-api-key }}" ]; then
          cat >> ~/.specular/config.yaml <<'INNEREOF'
          anthropic:
            api_key: ${{ inputs.anthropic-api-key }}
        INNEREOF
        fi

        if [ -n "${{ inputs.openai-api-key }}" ]; then
          cat >> ~/.specular/config.yaml <<'INNEREOF'
          openai:
            api_key: ${{ inputs.openai-api-key }}
        INNEREOF
        fi

        if [ -n "${{ inputs.google-api-key }}" ]; then
          cat >> ~/.specular/config.yaml <<'INNEREOF'
          google:
            api_key: ${{ inputs.google-api-key }}
        INNEREOF
        fi

    - name: Run Specular Command
      id: specular
      shell: bash
      run: |
        set +e  # Don't exit on error, we'll handle it

        COMMAND="${{ inputs.command }}"
        ARGS="${{ inputs.additional-args }}"

        case "$COMMAND" in
          drift)
            OUTPUT_FILE="${{ inputs.sarif-output }}"
            specular drift detect \
              --spec "${{ inputs.spec-file }}" \
              --plan "${{ inputs.plan-file }}" \
              --format sarif \
              --output "$OUTPUT_FILE" \
              $ARGS
            EXIT_CODE=$?

            # Parse SARIF for metrics
            if [ -f "$OUTPUT_FILE" ]; then
              DRIFT_COUNT=$(jq '.runs[0].results | length' "$OUTPUT_FILE" 2>/dev/null || echo "0")
              echo "drift-count=$DRIFT_COUNT" >> $GITHUB_OUTPUT
              echo "sarif-file=$OUTPUT_FILE" >> $GITHUB_OUTPUT
            fi
            ;;

          eval)
            specular eval run \
              --plan "${{ inputs.plan-file }}" \
              --policy "${{ inputs.policy-file }}" \
              --fail-on "${{ inputs.fail-on }}" \
              $ARGS
            EXIT_CODE=$?
            ;;

          build)
            specular build run \
              --plan "${{ inputs.plan-file }}" \
              --policy "${{ inputs.policy-file }}" \
              $ARGS
            EXIT_CODE=$?
            ;;

          plan)
            specular plan create \
              --in "${{ inputs.spec-file }}" \
              --out "${{ inputs.plan-file }}" \
              $ARGS
            EXIT_CODE=$?
            ;;

          *)
            echo "Unknown command: $COMMAND"
            echo "Supported commands: drift, eval, build, plan"
            exit 1
            ;;
        esac

        # Set result output
        if [ $EXIT_CODE -eq 0 ]; then
          echo "result=success" >> $GITHUB_OUTPUT
        else
          echo "result=failure" >> $GITHUB_OUTPUT
        fi

        exit $EXIT_CODE

    - name: Upload SARIF Results
      if: inputs.upload-sarif == 'true' && steps.specular.outputs.sarif-file != ''
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.specular.outputs.sarif-file }}
        category: specular-${{ inputs.command }}
      continue-on-error: true

    - name: Generate Job Summary
      if: always()
      shell: bash
      run: |
        echo "## Specular CI Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Command**: ${{ inputs.command }}" >> $GITHUB_STEP_SUMMARY
        echo "**Result**: ${{ steps.specular.outputs.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ -n "${{ steps.specular.outputs.drift-count }}" ]; then
          echo "**Drift Violations**: ${{ steps.specular.outputs.drift-count }}" >> $GITHUB_STEP_SUMMARY
        fi

        if [ -n "${{ steps.specular.outputs.test-count }}" ]; then
          echo "**Test Failures**: ${{ steps.specular.outputs.test-count }}" >> $GITHUB_STEP_SUMMARY
        fi

        if [ -n "${{ steps.specular.outputs.security-count }}" ]; then
          echo "**Security Issues**: ${{ steps.specular.outputs.security-count }}" >> $GITHUB_STEP_SUMMARY
        fi
