name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With configuration '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The command should have...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, it...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Output
      description: Relevant command output, error messages, or stack traces
      placeholder: Paste logs here (use ``` for code blocks)
      render: shell

  - type: input
    id: version
    attributes:
      label: Specular Version
      description: Output of `specular version`
      placeholder: v1.0.0
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: go version go1.22.0 darwin/arm64
    validations:
      required: true

  - type: input
    id: docker-version
    attributes:
      label: Docker Version
      description: Output of `docker version` (if relevant)
      placeholder: Docker version 24.0.0

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Specific version of your operating system
      placeholder: macOS 14.0, Ubuntu 22.04, Windows 11

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration files (policy.yaml, spec.yaml, etc.)
      placeholder: |
        ```yaml
        # Your configuration here
        ```
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might help
      placeholder: Add any other context about the problem here

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all requested information
          required: true
        - label: I have removed any sensitive information from logs/configs
          required: true
