package quickstart

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// ConfigFiles represents the generated configuration files
type ConfigFiles struct {
	RouterPath   string
	PolicyPath   string
	SettingsPath string
}

// GenerateMinimalConfig creates the minimum configuration needed for quickstart
func GenerateMinimalConfig(provider *ProviderSelection, docker DockerStatus) (*ConfigFiles, error) {
	specDir := ".specular"

	// Create .specular directory with secure permissions
	if err := os.MkdirAll(specDir, 0750); err != nil {
		return nil, fmt.Errorf("failed to create .specular directory: %w", err)
	}

	files := &ConfigFiles{
		RouterPath:   filepath.Join(specDir, "router.yaml"),
		PolicyPath:   filepath.Join(specDir, "policy.yaml"),
		SettingsPath: filepath.Join(specDir, "settings.json"),
	}

	// Generate router.yaml
	routerContent := generateRouterYAML(provider)
	if err := os.WriteFile(files.RouterPath, routerContent, 0600); err != nil {
		return nil, fmt.Errorf("failed to write router.yaml: %w", err)
	}

	// Generate policy.yaml
	policyContent := generatePolicyYAML(docker)
	if err := os.WriteFile(files.PolicyPath, policyContent, 0600); err != nil {
		return nil, fmt.Errorf("failed to write policy.yaml: %w", err)
	}

	// Generate settings.json
	settingsContent, err := generateSettingsJSON(provider, docker)
	if err != nil {
		return nil, fmt.Errorf("failed to generate settings.json: %w", err)
	}
	if err := os.WriteFile(files.SettingsPath, settingsContent, 0600); err != nil {
		return nil, fmt.Errorf("failed to write settings.json: %w", err)
	}

	return files, nil
}

// generateRouterYAML creates minimal router configuration
func generateRouterYAML(provider *ProviderSelection) []byte {
	// Use templates based on provider type
	switch provider.Type {
	case "api":
		return []byte(fmt.Sprintf(`# Specular Router Configuration
# Generated by: specular quickstart
# Provider: %s

# Budget limits (conservative defaults)
budget:
  max_cost: 5.0        # Maximum daily cost in USD
  warn_threshold: 0.5  # Warn at 50%% budget usage

# Provider configuration
providers:
  - name: %s
    enabled: true
    type: api
    # API key read from %s environment variable
`, provider.Name, provider.Name, provider.EnvVar))

	case "local":
		return []byte(fmt.Sprintf(`# Specular Router Configuration
# Generated by: specular quickstart
# Provider: %s (local)

# Budget limits (no cost for local models)
budget:
  max_cost: 0.0  # Local models have no API cost

# Provider configuration
providers:
  - name: %s
    enabled: true
    type: local
    endpoint: http://localhost:11434
    # Default model - change as needed
    model: llama3.2
    models:
      fast: llama3.2
      capable: llama3.2
      codegen: codellama
`, provider.Name, provider.Name))

	case "cli":
		return []byte(fmt.Sprintf(`# Specular Router Configuration
# Generated by: specular quickstart
# Provider: %s (CLI)

# Budget limits
budget:
  max_cost: 5.0  # Maximum daily cost in USD

# Provider configuration
providers:
  - name: %s
    enabled: true
    type: cli
    # Uses claude CLI from PATH
`, provider.Name, provider.Name))

	default:
		return []byte(fmt.Sprintf(`# Specular Router Configuration
# Generated by: specular quickstart

budget:
  max_cost: 5.0

providers:
  - name: %s
    enabled: true
    type: %s
`, provider.Name, provider.Type))
	}
}

// generatePolicyYAML creates permissive default policy for quickstart
func generatePolicyYAML(docker DockerStatus) []byte {
	dockerRequired := "false"
	dockerNote := "# Docker not detected - running without sandbox"
	if docker.Available {
		dockerRequired = "true"
		dockerNote = "# Docker available - sandboxed execution enabled"
	}

	return []byte(fmt.Sprintf(`# Specular Policy Configuration
# Generated by: specular quickstart
#
# This is a permissive default policy for getting started.
# For production use, enable stricter settings.

# Execution environment
execution:
  docker:
    required: %s  %s
    # Allowed Docker images (when docker is enabled)
    image_allowlist:
      - "golang:*"
      - "node:*"
      - "python:*"
      - "alpine:*"
    # Resource limits
    cpu_limit: "2"
    mem_limit: "2g"
    timeout: "10m"

# Testing requirements (relaxed for quickstart)
tests:
  require_pass: false  # Don't fail on test failures initially
  min_coverage: 0.0    # No coverage requirement

# Security checks
security:
  secrets_scan: true   # Warn about potential secrets
  dep_scan: false      # Skip dependency scanning for speed

# Approval settings
approval:
  require_human: false  # Auto-approve for quickstart
  # Set to true for production workflows
`, dockerRequired, dockerNote))
}

// Settings represents the quickstart settings metadata
type Settings struct {
	Version     string    `json:"version"`
	GeneratedAt time.Time `json:"generated_at"`
	GeneratedBy string    `json:"generated_by"`
	Provider    struct {
		Name   string `json:"name"`
		Type   string `json:"type"`
		Reason string `json:"reason"`
	} `json:"provider"`
	Docker struct {
		Available bool   `json:"available"`
		Runtime   string `json:"runtime,omitempty"`
		Version   string `json:"version,omitempty"`
	} `json:"docker"`
	Quickstart struct {
		CompletedAt time.Time `json:"completed_at"`
		Profile     string    `json:"profile"`
	} `json:"quickstart"`
}

// generateSettingsJSON creates metadata about the quickstart setup
func generateSettingsJSON(provider *ProviderSelection, docker DockerStatus) ([]byte, error) {
	settings := Settings{
		Version:     "1.0",
		GeneratedAt: time.Now().UTC(),
		GeneratedBy: "specular quickstart",
	}

	settings.Provider.Name = provider.Name
	settings.Provider.Type = provider.Type
	settings.Provider.Reason = provider.Reason

	settings.Docker.Available = docker.Available
	settings.Docker.Runtime = docker.Runtime
	settings.Docker.Version = docker.Version

	settings.Quickstart.CompletedAt = time.Now().UTC()
	settings.Quickstart.Profile = "quickstart"

	return json.MarshalIndent(settings, "", "  ")
}

// ConfigExists checks if Specular configuration already exists
func ConfigExists() bool {
	specDir := ".specular"

	// Check for any existing config files
	files := []string{"router.yaml", "policy.yaml", "providers.yaml", "spec.yaml"}
	for _, f := range files {
		if _, err := os.Stat(filepath.Join(specDir, f)); err == nil {
			return true
		}
	}

	return false
}

// BackupExistingConfig backs up existing configuration before overwriting
func BackupExistingConfig() (string, error) {
	specDir := ".specular"
	backupDir := fmt.Sprintf(".specular.backup.%d", time.Now().Unix())

	if err := os.Rename(specDir, backupDir); err != nil {
		return "", fmt.Errorf("failed to backup existing config: %w", err)
	}

	return backupDir, nil
}
