package provider

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLoadProvidersConfigFromBytesExpandsEnv(t *testing.T) {
	os.Setenv("SPECULAR_TEST_PATH", "/usr/bin/true")
	defer os.Unsetenv("SPECULAR_TEST_PATH")

	raw := `
providers:
  - name: test-cli
    type: cli
    enabled: true
    config:
      path: ${SPECULAR_TEST_PATH}
`

	cfg, err := LoadProvidersConfigFromBytes([]byte(raw))
	if err != nil {
		t.Fatalf("LoadProvidersConfigFromBytes() error = %v", err)
	}

	if len(cfg.Providers) != 1 {
		t.Fatalf("expected 1 provider, got %d", len(cfg.Providers))
	}

	if path, _ := cfg.Providers[0].Config["path"].(string); path != "/usr/bin/true" {
		t.Fatalf("expected path expanded to /usr/bin/true, got %q", path)
	}
}

func TestValidateProvidersConfigRequiresEnabledProvider(t *testing.T) {
	cfg := &ProvidersConfig{
		Providers: []ProviderConfig{
			{
				Name:    "broken",
				Type:    ProviderTypeCLI,
				Enabled: false,
				Config: map[string]interface{}{
					"path": "/bin/true",
				},
			},
		},
	}

	if err := ValidateProvidersConfig(cfg); err == nil {
		t.Fatal("expected error when no provider is enabled")
	}
}

func TestValidateProvidersConfigRejectsNegativeStrategy(t *testing.T) {
	badStrategy := &ProvidersConfig{
		Providers: []ProviderConfig{
			{
				Name:    "good",
				Type:    ProviderTypeCLI,
				Enabled: true,
				Config: map[string]interface{}{
					"path": "/bin/true",
				},
			},
		},
		Strategy: StrategyConfig{
			Budget: BudgetConfig{
				MaxCostPerDay:     -1.0,
				MaxCostPerRequest: -1.0,
			},
			Performance: PerformanceConfig{
				MaxLatencyMs: -1,
			},
			Fallback: FallbackConfig{
				MaxRetries:   -1,
				RetryDelayMs: -1,
			},
		},
	}

	if err := ValidateProvidersConfig(badStrategy); err == nil {
		t.Fatal("expected error for negative budget/performance/fallback values")
	}
}

func TestApplyRecommendedProvidersFallback(t *testing.T) {
	cfg := ConfigFromRecommended([]string{"nonexistent"})
	ApplyRecommendedProviders(cfg, []string{"still-missing"})

	enabled := 0
	for _, provider := range cfg.Providers {
		if provider.Enabled {
			enabled++
		}
	}
	if enabled != 1 {
		t.Fatalf("expected exactly one provider enabled after fallback, got %d", enabled)
	}
}

func TestWriteProvidersConfigFromDescriptorsCreatesFile(t *testing.T) {
	tmpDir := t.TempDir()
	target := filepath.Join(tmpDir, "providers.yaml")

	cfg, err := WriteProvidersConfigFromDescriptors(target, []string{"ollama"})
	if err != nil {
		t.Fatalf("WriteProvidersConfigFromDescriptors() error = %v", err)
	}

	if cfg == nil {
		t.Fatal("expected a config to be returned")
	}

	if _, err := os.Stat(target); err != nil {
		t.Fatalf("expected providers file to exist, got error: %v", err)
	}
}

func TestSaveProvidersConfigExample(t *testing.T) {
	tmpDir := t.TempDir()
	target := filepath.Join(tmpDir, "providers.example.yaml")

	if err := SaveProvidersConfigExample(DefaultProvidersConfig(), target); err != nil {
		t.Fatalf("SaveProvidersConfigExample() error = %v", err)
	}

	data, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("failed to read generated example: %v", err)
	}

	if !strings.Contains(string(data), "# Example provider configuration generated by specular") {
		t.Fatalf("example file missing header, got %s", string(data))
	}

	if err := SaveProvidersConfigExample(nil, target); err == nil {
		t.Fatal("expected error when config is nil")
	}
}
